--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9 (Ubuntu 16.9-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.9 (Ubuntu 16.9-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: reports; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.reports (id, name, slug, title, description, data_source, enabled, last_generated_at, run_at, run_every, published, rank, created_at, updated_at) VALUES (18, 'MenageOrdinaire/EasWithoutDisabilityRegister', 'menage-ordinaire.eas-without-disability-register', '{"en": "List of EAs without disability record register", "fr": "Liste des ZDs sans une personne handicapée"}', '{"en": "List of EAs without disability record register", "fr": "Liste des ZDs sans une personne handicapée"}', 'menage_ordinaire', true, '2025-05-29 12:07:46', '00:00:00', 24, true, NULL, '2025-05-24 12:45:07', '2025-05-29 12:07:46') ON CONFLICT DO NOTHING;
INSERT INTO public.reports (id, name, slug, title, description, data_source, enabled, last_generated_at, run_at, run_every, published, rank, created_at, updated_at) VALUES (20, 'MenageOrdinaire/PartialCasesByEa', 'menage-ordinaire.partial-cases-by-ea', '{"en": "EAs with number of partial cases", "fr": "Questionnaires partiellement remplis"}', '{"en": "EAs with number of partial cases", "fr": "Questionnaires partiellement remplis"}', 'menage_ordinaire', true, '2025-05-29 12:07:46', '00:00:00', 24, true, NULL, '2025-05-24 12:50:51', '2025-05-29 12:07:46') ON CONFLICT DO NOTHING;
INSERT INTO public.reports (id, name, slug, title, description, data_source, enabled, last_generated_at, run_at, run_every, published, rank, created_at, updated_at) VALUES (19, 'MenageOrdinaire/WronglyDatedCases', 'menage-ordinaire.wrongly-dated-cases', '{"en": "List of EAs that sent wrongly dated cases", "fr": "Liste des ZDs dont les donnees sont envoyées avec des datés erronées"}', '{"en": "List of EAs that sent wrongly dated cases", "fr": "Liste des ZDs dont les donnees sont envoyées avec des datés erronées"}', 'menage_ordinaire', true, '2025-05-29 12:07:47', '00:00:00', 24, true, NULL, '2025-05-24 12:49:18', '2025-05-29 12:07:47') ON CONFLICT DO NOTHING;
INSERT INTO public.reports (id, name, slug, title, description, data_source, enabled, last_generated_at, run_at, run_every, published, rank, created_at, updated_at) VALUES (13, 'MenageOrdinaire/DuplicateCasesByEa', 'menage-ordinaire.duplicate-cases-by-ea', '{"en": "List of duplicated questionnaire(cases) by EA", "fr": "Liste des questionnaires (doublons) par ZD"}', '{"en": "List of questionnaire(cases) by EA", "fr": "Liste des questionnaires (doublons) par ZD"}', 'menage_ordinaire', true, '2025-05-29 12:07:59', '00:00:00', 24, true, NULL, '2025-05-24 12:36:46', '2025-05-29 12:07:59') ON CONFLICT DO NOTHING;
INSERT INTO public.reports (id, name, slug, title, description, data_source, enabled, last_generated_at, run_at, run_every, published, rank, created_at, updated_at) VALUES (15, 'MenageOrdinaire/EasWithLowPerformance', 'menage-ordinaire.eas-with-low-performance', '{"en": "List of EAs with low performance", "fr": "ZDs à faible performance a ce jour"}', '{"en": "List of EAs with low performance", "fr": "ZDs à faible performance a ce jour"}', 'menage_ordinaire', true, '2025-05-29 12:08:00', '00:00:00', 24, true, NULL, '2025-05-24 12:42:38', '2025-05-29 12:08:00') ON CONFLICT DO NOTHING;
INSERT INTO public.reports (id, name, slug, title, description, data_source, enabled, last_generated_at, run_at, run_every, published, rank, created_at, updated_at) VALUES (5, 'MenageOrdinaire/EasNotStartedEnumeration', 'menage-ordinaire.eas-not-started-enumeration', '{"en": "Zds qui n''ont pas commencé le dénombrement", "fr": "Zds qui n''ont pas commencé le dénombrement"}', '{"en": "Zds qui n''ont pas commencé le dénombrement", "fr": "Zds qui n''ont pas commencé le dénombrement"}', 'menage_ordinaire', true, '2025-05-29 12:08:01', '00:00:00', 24, true, NULL, '2025-03-09 09:04:13', '2025-05-29 12:08:01') ON CONFLICT DO NOTHING;
INSERT INTO public.reports (id, name, slug, title, description, data_source, enabled, last_generated_at, run_at, run_every, published, rank, created_at, updated_at) VALUES (11, 'MenageOrdinaire/AverageHhSizeByEa', 'menage-ordinaire.average-hh-size-by-ea', '{"en": "Average household by EA", "fr": "Taille moyenne des ménages par ZD"}', '{"en": "Average household by EA", "fr": "Taille moyenne des ménages par ZD"}', 'menage_ordinaire', true, '2025-05-29 12:08:02', '00:00:00', 24, true, NULL, '2025-05-24 12:34:29', '2025-05-29 12:08:02') ON CONFLICT DO NOTHING;
INSERT INTO public.reports (id, name, slug, title, description, data_source, enabled, last_generated_at, run_at, run_every, published, rank, created_at, updated_at) VALUES (7, 'Concession/EaNotStartedListing', 'concession.ea-not-started-listing', '{"en": "List of EAs not started listing yet", "fr": "Liste des ZDs dont la concreatization n''a pas encore commence"}', '{"en": "List of EAs not started listing yet", "fr": "Liste des ZDs dont la concreatization n''a pas encore commence"}', 'listing', true, '2025-05-29 12:08:03', '00:00:00', 24, true, NULL, '2025-05-23 11:59:44', '2025-05-29 12:08:03') ON CONFLICT DO NOTHING;
INSERT INTO public.reports (id, name, slug, title, description, data_source, enabled, last_generated_at, run_at, run_every, published, rank, created_at, updated_at) VALUES (2, 'Concession/LastSyncedNotRecent', 'concession.last-synced-not-recent', '{"en": "Dernière synchronisation de plus de 24 heures", "fr": "La liste des zd ou la synchronisation n''est pas faite il y''a plus de 24 heures"}', '{"en": "Dernière synchronisation de plus de 24 heures\n", "fr": "La liste des zd ou la synchronisation n''est pas faite il y''a plus de 24 heures"}', 'listing', true, '2025-05-29 12:07:44', '00:00:00', 24, true, NULL, '2025-03-06 05:53:16', '2025-05-29 12:07:44') ON CONFLICT DO NOTHING;
INSERT INTO public.reports (id, name, slug, title, description, data_source, enabled, last_generated_at, run_at, run_every, published, rank, created_at, updated_at) VALUES (3, 'Concession/PartialByEA', 'concession.partial-by-e-a', '{"en": "Cas Partiels", "fr": "Questionnaires partiellement remplis"}', '{"en": "Cas Partiels\n", "fr": "Questionnaires partiellement remplis"}', 'listing', true, '2025-05-29 12:07:44', '00:00:00', 24, true, NULL, '2025-03-06 05:56:48', '2025-05-29 12:07:44') ON CONFLICT DO NOTHING;
INSERT INTO public.reports (id, name, slug, title, description, data_source, enabled, last_generated_at, run_at, run_every, published, rank, created_at, updated_at) VALUES (16, 'MenageOrdinaire/EasWithoutBirthRegister', 'menage-ordinaire.eas-without-birth-register', '{"en": "List of EAs without birth record register", "fr": "Liste des ZDs sans une naissance des 12 dernier mois"}', '{"en": "List of EAs without birth record register", "fr": "Liste des ZDs sans une naissance des 12 dernier mois"}', 'menage_ordinaire', true, '2025-05-29 12:07:45', '00:00:00', 24, true, NULL, '2025-05-24 12:43:36', '2025-05-29 12:07:45') ON CONFLICT DO NOTHING;
INSERT INTO public.reports (id, name, slug, title, description, data_source, enabled, last_generated_at, run_at, run_every, published, rank, created_at, updated_at) VALUES (6, 'MenageOrdinaire/EnumeratorPerformanceWithDate', 'menage-ordinaire.enumerator-performance-with-date', '{"en": "Performance de l''agent recenseur avec date", "fr": "Performance de l''agent recenseur par jour"}', '{"en": "Performance de l''agent recenseur avec date", "fr": "Performance de l''agent recenseur par jour"}', 'menage_ordinaire', true, '2025-05-29 12:07:55', '00:00:00', 24, true, NULL, '2025-03-09 09:06:39', '2025-05-29 12:07:55') ON CONFLICT DO NOTHING;
INSERT INTO public.reports (id, name, slug, title, description, data_source, enabled, last_generated_at, run_at, run_every, published, rank, created_at, updated_at) VALUES (1, 'MenageOrdinaire/LastSyncNotRecent', 'menage-ordinaire.last-sync-not-recent', '{"en": "Dernière synchronisation de plus de 24 heures", "fr": "La liste des zd ou la synchronisation n''est pas faite il y''a plus de 24 heures"}', '{"en": "Dernière synchronisation de plus de 24 heures\n", "fr": "La liste des zd ou la synchronisation n''est pas faite il y''a plus de 24 heures"}', 'menage_ordinaire', true, '2025-05-29 12:07:59', '00:00:00', 24, true, NULL, '2025-03-06 05:52:44', '2025-05-29 12:07:59') ON CONFLICT DO NOTHING;
INSERT INTO public.reports (id, name, slug, title, description, data_source, enabled, last_generated_at, run_at, run_every, published, rank, created_at, updated_at) VALUES (9, 'Concession/EasWithLowPerformace', 'concession.eas-with-low-performace', '{"en": "Eas with low performance", "fr": "ZDs à faible performance a ce jour"}', '{"en": "Eas with low performance", "fr": "Eas with low performance"}', 'listing', true, '2025-05-29 12:08:05', '00:00:00', 24, true, NULL, '2025-05-23 12:30:06', '2025-05-29 12:08:05') ON CONFLICT DO NOTHING;
INSERT INTO public.reports (id, name, slug, title, description, data_source, enabled, last_generated_at, run_at, run_every, published, rank, created_at, updated_at) VALUES (12, 'MenageOrdinaire/AverageInterviewTimeByEa', 'menage-ordinaire.average-interview-time-by-ea', '{"en": "Average interview time by EA", "fr": "Durée moyenne des interview par ZD"}', '{"en": "Average interview time by EA", "fr": "Durée moyenne des interview par ZD"}', 'menage_ordinaire', true, '2025-05-29 12:08:07', '00:00:00', 24, true, NULL, '2025-05-24 12:35:12', '2025-05-29 12:08:07') ON CONFLICT DO NOTHING;
INSERT INTO public.reports (id, name, slug, title, description, data_source, enabled, last_generated_at, run_at, run_every, published, rank, created_at, updated_at) VALUES (8, 'Concession/DuplicatedCases', 'concession.duplicated-cases', '{"en": "Duplicated cases", "fr": "Liste des questionnaires (doublons) par ZD"}', '{"en": "Duplicated cases", "fr": "Liste des questionnaires (doublons) par ZD"}', 'listing', true, '2025-05-29 12:08:08', '00:00:00', 24, true, NULL, '2025-05-23 12:05:21', '2025-05-29 12:08:08') ON CONFLICT DO NOTHING;
INSERT INTO public.reports (id, name, slug, title, description, data_source, enabled, last_generated_at, run_at, run_every, published, rank, created_at, updated_at) VALUES (17, 'MenageOrdinaire/EasWithoutDeathRegister', 'menage-ordinaire.eas-without-death-register', '{"en": "List of EAs without death record register", "fr": "Liste des ZDs sans un décès des 12 dernier mois"}', '{"en": "List of EAs without death record register", "fr": "Liste des ZDs sans un décès des 12 dernier mois"}', 'menage_ordinaire', true, '2025-05-29 12:08:09', '00:00:00', 24, true, NULL, '2025-05-24 12:44:14', '2025-05-29 12:08:09') ON CONFLICT DO NOTHING;
INSERT INTO public.reports (id, name, slug, title, description, data_source, enabled, last_generated_at, run_at, run_every, published, rank, created_at, updated_at) VALUES (10, 'Concession/HhWithHighHouseholdSize', 'concession.hh-with-high-household-size', '{"en": "List of households with high householdsize", "fr": "Liste des ménages de grande taille"}', '{"en": "List of households with high householdsize", "fr": "Liste des ménages de grande taille"}', 'listing', true, NULL, '00:00:00', 24, true, NULL, '2025-05-23 12:31:48', '2025-05-29 09:50:12') ON CONFLICT DO NOTHING;
INSERT INTO public.reports (id, name, slug, title, description, data_source, enabled, last_generated_at, run_at, run_every, published, rank, created_at, updated_at) VALUES (14, 'MenageOrdinaire/EasAchievedEnumerationTarget', 'menage-ordinaire.eas-achieved-enumeration-target', '{"en": "List of EAs that achieved the enumeration target", "fr": "Liste des ZDs ayant atteint l’objectif de dénombrement - par rapport au concession existant"}', '{"en": "List of EAs that achieved the enumeration target", "fr": "Liste des ZDs ayant atteint l’objectif de dénombrement - par rapport au concession existant"}', 'menage_ordinaire', true, '2025-05-29 12:08:10', '00:00:00', 24, true, NULL, '2025-05-24 12:39:34', '2025-05-29 12:08:10') ON CONFLICT DO NOTHING;


--
-- Name: reports_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reports_id_seq', 20, true);


--
-- PostgreSQL database dump complete
--

